<?php
// echo "<pre>";

                // print_r($block->getFilteredCustomerCollection()->getData()); die;
/**
 * @var $block \Born\MultiUsers\Block\Adminhtml\CustomerEdit\Tab\View
 */
?>

<div class="fieldset-wrapper customer-information">
    <div class="fieldset-wrapper-title">
        <span class="title"><?php /* @escapeNotVerified */
        echo __('Information of Child Customers') ?></span>
    </div>
        <table class="admin__table-secondary child-customer-accounts-table">
            <thead>
                <?php echo $block->getChildHtml(); ?>
                <tr>
                    <th><?php /* @escapeNotVerified */
                    echo __('Customer ID') ?></th>
                    <th><?php /* @escapeNotVerified */
                    echo __('Customer Name') ?></th>
                    <th><?php /* @escapeNotVerified */
                    echo __('Customer Email') ?></th>
                    <th><?php /* @escapeNotVerified */
                    echo __('permission') ?></th>
                    <th><?php /* @escapeNotVerified */
                    echo __('Status') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($block->getFilteredCustomerCollection() as $childCustomer) {?>
                    <tr>
                        <td><?php /* @escapeNotVerified */echo __($childCustomer->getEntityId()) ?></th>
                            <td><?php echo __($childCustomer->getFirstname().' '.$childCustomer->getLastname()) ?></td>
                            <td><?php echo __($childCustomer->getEmail()) ?></td>
                            <td><?php echo __('to be implemeneted..') ?></td>
                            <?php if ($childCustomer->getIsActive() == 1) {?>
                                <td><?php echo __('Active') ?></td>
                            <?php  }else{ ?>
                                <td><?php echo __('Not Active') ?></td>
                            <?php } ?>
                        </tr>
                    <?php  } ?>
                </tbody>
        </table>
</div>
<div>
    
    <a href="#"><span>Add Sub Account</span></a>
</div>


<!-- Will remove this and will put in css file -->
<style type="text/css">

.child-customer-accounts-table{
    width: 100% !important;
}
.child-customer-accounts-table thead{
    background: #41362f;
}
.child-customer-accounts-table th{
    color: white;
}
</style>